# Generated by Django 4.0.5 on 2023-11-05 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_comentarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentarios',
            old_name='content',
            new_name='contenido',
        ),
    ]
