# Generated by Django 4.0.5 on 2023-11-07 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_rename_content_comentarios_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitulos',
            name='orden',
            field=models.IntegerField(default=0),
        ),
    ]
