# Generated by Django 4.0.5 on 2023-11-10 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_usuario_options_alter_usuario_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obra',
            old_name='foto_perfil',
            new_name='foto_obra',
        ),
    ]
