# Generated by Django 4.0.5 on 2023-11-10 15:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_rename_foto_perfil_obra_foto_obra'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='sobre_mi',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
