# Generated by Django 4.0.5 on 2023-11-11 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_usuario_sobre_mi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obra',
            old_name='descripcion',
            new_name='sinopsis',
        ),
    ]
