# Generated by Django 4.0.5 on 2023-11-12 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_rename_descripcion_obra_sinopsis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentarios',
            name='obra',
        ),
        migrations.AddField(
            model_name='comentarios',
            name='capitulo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.capitulos'),
            preserve_default=False,
        ),
    ]
