# Generated by Django 4.0.5 on 2023-11-12 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_remove_comentarios_obra_comentarios_capitulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tumblr',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='LinkRedesSociales',
        ),
    ]
