# Generated by Django 4.0.5 on 2023-11-13 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_like'),
        ('polls', '0012_obra_search_vector_and_more'),
    ]

    operations = [
    ]
