# Generated by Django 4.0.5 on 2023-11-13 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_merge_0012_like_0012_obra_search_vector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='capitulo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='capitulo_likes', to='polls.capitulos'),
            preserve_default=False,
        ),
    ]
