# Generated by Django 4.0.5 on 2023-11-13 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_like_capitulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='obra',
        ),
    ]
