# Generated by Django 4.0.5 on 2023-11-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_remove_like_obra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='sobre_mi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
